### ISSUE TITLE
Follow type

### ISSUE THREAD

**Issue by cescoferraro** [zmb3/spotify#16]
This line is buggy
https://github.com/zmb3/spotify/blob/master/user.go#L210

ids parameter value is missing. and the type is mandatory.
https://developer.spotify.com/web-api/follow-artists-users/

this works
`spotifyURL := baseAddress + "me/following?type=artist&ids=" + strings.Join(toStringSlice(ids), ",")`

I can submit a PR for this, but want to know what do you consider being the best way of tackling this.

Both Follow and UNfollow use the same `modifyFollowers` and take  ids as varaidic arguments.
Shoud them take type as an argument? I think so. Following multiple people of different types would probably fail. SHould it be documented?

**Comment by zmb3** [comment]
What if we make FollowArtists and FollowUsers, each of which would pass the
correct type to modifyFollowers, and then we can deprecate the original
follow funcs?

On Wed, Nov 30, 2016 at 10:06 AM cesco <notifications@github.com> wrote:

This line is buggy
https://github.com/zmb3/spotify/blob/master/user.go#L210

ids parameter value is missing. and the type is mandatory.
https://developer.spotify.com/web-api/follow-artists-users/

this works
spotifyURL := baseAddress + "me/following?type=artist&ids=" +
strings.Join(toStringSlice(ids), ",")

I can submit a PR for this, but want to know what do you consider being the
best way of tackling this.

Both Follow and UNfollow use the same modifyFollowers and take ids as
varaidic arguments.
Shoud them take type as an argument? I think so. Following multiple people
of different types would probably fail. SHould it be documented?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zmb3/spotify/issues/16>, or mute the thread

**Comment by cescoferraro** [comment]
i will write this later today @zmb3

**Comment by zmb3** [comment]
Fixed by #18
