### ISSUE TITLE
GetShow() returns "non existing id"

### ISSUE THREAD

**Issue by sa7mon** [zmb3/spotify#187]
Here's my PoC code trying to fetch info about a show:

```golang
ctx := context.Background()
config := &clientcredentials.Config{
	ClientID:     os.Getenv("SPOTIFY_ID"),
	ClientSecret: os.Getenv("SPOTIFY_SECRET"),
	TokenURL:     spotifyauth.TokenURL,
}
token, err := config.Token(ctx)
if err != nil {
	log.Fatalf("couldn't get token: %v", err)
}

httpClient := spotifyauth.New().Client(ctx, token)
client := spotify.New(httpClient)

show, err := client.GetShow(ctx, "6kAsbP8pxwaU2kPibKTuHE")
if err != nil {
	log.Fatal(err)
}

j, err := json.Marshal(show)
if err != nil {
	log.Fatal(err)
}
fmt.Println(string(j))
```

When I run it, I get the line "non existing id" logged after the `GetShow()` call. I know for sure this show exists, as you can navigate to it on the web [here](https://open.spotify.com/show/6kAsbP8pxwaU2kPibKTuHE)

Am I doing something wrong?

**Comment by strideynet** [comment]
I've reproduced this as code, and found a work-around.

It looks like they require the market to be specified when fetching a show. e.g 

```go
	show, err := client.GetShow(ctx, "0azMejb7zrmAqctVsUSAdq", spotify.Market(spotify.CountryUnitedKingdom))
	if err != nil {
		log.Fatal(err)
	}
```

I can only hazard a guess that when a token linked to a user is used, they default to the market associated with the user, which is why the online API dashboard works fine.

I'll keep this issue open and add a godoc comment to note this behaviour.

**Comment by sa7mon** [comment]
Awesome, this totally fixes it! Thank, I really thought I was going to have to shell out to a Python library to do the auth which I *really* didn't want to do

**Comment by JOY2OP** [comment]
This worked for me too. THANKS.
Spend a lot of time on this. Can you put this into your documentation?
